name: NASA Project CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        env:
            CI: true
            MONGO_URL: mongodb://localhost/nasa
            GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
            GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
            COOKIE_NAME: ${{secrets.COOKIE_NAME}}
            COOKIE_KEY_1: ${{secrets.COOKIE_KEY_1}}
            COOKIE_KEY_2: ${{secrets.COOKIE_KEY_2}}
            COOKIE_MAX_AGE: ${secrets.COOKIE_MAX_AGE}
        strategy:
            matrix:
                node-version: [23.x, 24.x]
                mongodb-version: ["8.0"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js version ${{matrix.node-version}}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{matrix.node-version}}
            - name: Use MongoDB from Github actions
              uses: supercharge/mongodb-github-action@1.12.1
              with:
                  mongodb-version: ${{matrix.mongodb-version}}
            - run: npm install
            - run: |
                  npm run build --prefix client
                  echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
                  echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
                  echo "COOKIE_NAME=$COOKIE_NAME" >> .env
                  echo "COOKIE_KEY_1=$COOKIE_KEY_1" >> .env
                  echo "COOKIE_KEY_2=$COOKIE_KEY_2" >> .env
                  echo "COOKIE_MAX_AGE=$COOKIE_MAX_AGE" >> .env
            - run: npm test
